trigger:
  batch: true
  branches:
    include: 
    - '*'
  paths:
    include: 
    - parrot/
    - common/ci-steps-template.yml
    - common/cd-steps-template.yml
pr: none

pool:
  vmImage: ubuntu-latest

variables:
- template: ../common/ci-vars-template.yml
- template: ../common/cd-vars-template.yml
  parameters:
      projectName: parrot
  # define 3 more variables: registryName, registryLogin and registryPassword in the build pipeline in UI

steps:
- template: ../common/ci-steps-template.yml
- template: ../common/cd-steps-template.yml