trigger:
  batch: true
  branches:
    include: 
    - '*'
  paths:
    include: 
    - parrot/
    - common/ci-steps-template.yml
pr: none

pool:
  vmImage: ubuntu-latest

variables:
- template: ../common/ci-vars-template.yml
  parameters:
      projectName: parrot
  # define 3 more variables: registryName, registryLogin and registryPassword in the build pipeline in UI

steps:
- template: ../common/ci-steps-template.yml
- bash: |
   az login --service-principal -u $(aksSpId) -p '$(aksSpSecret)' --tenant $(aksSpTenantId)
   az aks get-credentials -n az-aks-vsblity-prod -g devops-dev-rg
   kubectl get nodes
   helm repo add vsblty.azurecr.io https://vsblty.azurecr.io/helm/v1/repo --username $(registryLogin) --password '$(registryPassword)'
   helm list
   ##helm repo add $(registryName) https://$(registryName)/helm/v1/repo --username $(registryLogin) --password '$(registryPassword)'
   helm upgrade --namespace dev --create-namespace --install --wait --version $(build.buildId) --set image.repository=vsblty.azurecr.io/$(projectName) --set ingress.enabled=false $(projectName) vsblty.azurecr.io/$(projectName)